---
title: "becca_exploration"
output: html_document
date: "2025-03-25"
---

```{r}

library(dplyr)
library(here)
library(tidyverse)

here()

fish <- read.csv("data/fish_data_all_becca.csv")

fish[fish == ''] <- NA

fish <- fish %>%
  filter(if_any(FO, ~ !(.x %in% c("yes", "no")))) %>%
  drop_na(FO)

fish$FO <- as.numeric(fish$FO)

fish_group <- fish %>%
  group_by(order) %>%
  summarize(mean_fo=mean(FO))

```

```{r}

fish_dist <- ggplot(fish, aes(x=FO)) +
  geom_histogram() +
  theme_bw() +
  theme(legend.position = "none")

fish_dist

```

## ANOVA

```{r}


#i didn't do variance

order_ANOVA <- aov(FO ~ order + family, data = fish)

summary(order_ANOVA)

tukey <- TukeyHSD(order_ANOVA)

library(broom)
library(dplyr)

tukey_table <- as.data.frame(tidy(tukey))

```

Significant difference in ANOVA, but none in Tukey's HSD.

```{r}

fish_clean <- read.csv("cleaner_fish_table_becca.csv")

library(dunn.test)

kruskal_test_order <- kruskal.test(FO ~ order, data = fish)

kruskal_test_order

dunn_test_order <- dunn.test(fish$FO, fish$order, list = TRUE)

dunn_test_order = cbind.data.frame(dunn_test_order$comparisons,dunn_test_order$Z,dunn_test_order$P.adjusted)

colnames(dunn_test_order) <- c("comparisons","Z", "P.adjusted")

dunn_test_order_sorted <- dunn_test_order %>%
  filter(P.adjusted < 0.05)

kruskal_test_family <- kruskal.test(FO ~ family, data = fish)

kruskal_test_family

dunn_test_family <- dunn.test(fish$FO, fish$family, list = TRUE)

dunn_test_family = cbind.data.frame(dunn_test_family$comparisons,dunn_test_family$Z,dunn_test_family$P.adjusted)

colnames(dunn_test_family) <- c("comparisons","Z", "P.adjusted")

dunn_test_family_sorted <- dunn_test_family %>%
  filter(P.adjusted < 0.05)



```


## Linear Model

```{r}

fish <- fish %>% separate(habitat, c('Neritic_Oceanic', 'Bentho_Pelagic'), sep=",")

fish[fish=="D"]<-"B"

#fish[fish == ' D'] <- "D"
fish[fish == ' B'] <- "B"
fish[fish == ' P'] <- "P"
fish[fish == ' BP'] <- "BP"
fish[fish == ' B '] <- "B"

write.csv(fish,file='cleaner_fish_table_becca.csv')

fish <- fish %>% drop_na(trophic_level) %>% drop_na(Neritic_Oceanic) %>% drop_na(Bentho_Pelagic)

mlm1 <- lm(FO ~ order + family + Neritic_Oceanic + Bentho_Pelagic + feeding_strategy + trophic_level, data = fish_clean) #not this one

AIC(mlm1)

summary(mlm1)

#plot(mlm1) # outliers not labelled?

# Run AIC

#step(mlm1)

#mlm2 <- lm(FO ~ order + family + Neritic_Oceanic + Bentho_Pelagic + feeding_strategy + trophic_level, data = outliers_rm)

#summary(mlm2)

#plot(mlm2)

#THIS ONE

mlm3 <- lm(FO ~ Neritic_Oceanic + Bentho_Pelagic + feeding_strategy, data = fish_clean)

summary(mlm3)

AIC(mlm3)

#plot(mlm3)

step(mlm3)

mlm4 <- lm(FO ~ Neritic_Oceanic, data = fish_clean)

summary(mlm4)

```

## GLM

```{r}

unique(fish$Neritic_Oceanic)

fish$Neritic_Oceanic <- factor(fish$Neritic_Oceanic,
                             levels = c("N-O",
                                        "N",
                                        "O"))

unique(fish$Bentho_Pelagic)

fish$Bentho_Pelagic <- factor(fish$Bentho_Pelagic,
                             levels = c("B",
                                        "P",
                                        "BP"))

unique(fish$feeding_strategy)

fish$feeding_strategy <- factor(fish$feeding_strategy,
                             levels = c("BP",
                                        "P",
                                        "PP",
                                        "O",
                                        "G"))

unique(fish$trophic_level)

fish$trophic_level <- as.numeric(fish$trophic_level, na.rm=TRUE)

fish_mod <- glm(FO~Neritic_Oceanic+Bentho_Pelagic+feeding_strategy+trophic_level,
                data = fish,
                family = "poisson")

summary(fish_mod)

#plot(fish_mod)

fishmod_2 <- fish[-c(15,273,123,122,128,27,26,48,72),] #a lot of outliers! this isn't all of them

fish_mod_2 <- glm(FO~Neritic_Oceanic+Bentho_Pelagic+feeding_strategy+trophic_level,
                 data = fishmod_2,
                 family = "poisson")

summary(fish_mod_2)

#plot(fish_mod_2)

```

## Predictive Model 1

```{r}

unique(fish$feeding_strategy)

fish <- fish %>% drop_na(feeding_strategy)

fish$binary <- ifelse(fish$FO > 0, "1", "0")

fish$binary <- as.numeric(fish$binary)

fish_mod_glm <- glm(binary~Neritic_Oceanic+Bentho_Pelagic+feeding_strategy+trophic_level,
                data = fish,
                family = "binomial")

summary(fish_mod_glm)

trophic_vector <- rep(seq(from = 2, to = 5, by = 0.1), 5)

#trophiclevel <- fish %>% select(trophic_level)

# sometimes I get 406, sometimes I get 403, now I have 405

#neritic_oceanic_vector <- c(rep("N-O", 135),
               #    rep("N", 135),
              #   rep("O", 135))

#bentho_pelagic_vector <- c(rep("B", 135),
          #       rep("P", 135),
          #       rep("BP", 135))


feeding_vector <- c(rep("BP", 31),
                   rep("P", 31),
                 rep("PP", 31),
                 rep("O", 31),
                     rep("G", 31))

neritic_oceanic_vector <- rep("N-O", 155)
bentho_pelagic_vector <- rep("BP", 155)

data_pred <- data.frame(trophic_vector, neritic_oceanic_vector, bentho_pelagic_vector, feeding_vector)
colnames(data_pred) <- c("trophic_level", "Neritic_Oceanic", "Bentho_Pelagic", "feeding_strategy")

prediction <- predict(fish_mod_glm,
                      newdata = data_pred,
                      type = "response",
                      se.fit = TRUE)


data_fig <- data.frame(data_pred,
                       prediction$fit,
                       prediction$se.fit)


colnames(data_fig) <- c("trophic_vector", "neritic_oceanic", "bentho_pelagic", "FeedingStrategy", "probability", "se")

library(ggplot2)

ggplot(data_fig, aes(x = trophic_vector,
                     y = probability)) +
  geom_line(aes(color = FeedingStrategy)) +
  geom_ribbon(aes(ymin = probability - se,
                  ymax = probability + se,
                  fill = FeedingStrategy), alpha = 0.3) +
  labs(x = "Trophic Level", y = "Probability of Occurrence", title = "Probability of Plastic Occurrence by Trophic Level According to Fish Feeding Strategy") +
  theme_bw()

```

## Predictive Model 2

```{r}

trophic_vector <- rep(seq(from = 2, to = 5, by = 0.1), 3)

feeding_vector <- c(rep("BP", 93))

neritic_oceanic_vector <- c(rep("N-O", 31),
                   rep("N", 31),
                rep("O", 31))

bentho_pelagic_vector <- rep("BP", 93)

data_pred <- data.frame(trophic_vector, neritic_oceanic_vector, bentho_pelagic_vector, feeding_vector)
colnames(data_pred) <- c("trophic_level", "Neritic_Oceanic", "Bentho_Pelagic", "feeding_strategy")

prediction <- predict(fish_mod_glm,
                      newdata = data_pred,
                      type = "response",
                      se.fit = TRUE)


data_fig <- data.frame(data_pred,
                       prediction$fit,
                       prediction$se.fit)


colnames(data_fig) <- c("trophic_vector", "NeriticOceanic", "bentho_pelagic", "feeding_strategy", "probability", "se")

library(ggplot2)

ggplot(data_fig, aes(x = trophic_vector,
                     y = probability)) +
  geom_line(aes(color = NeriticOceanic)) +
  geom_ribbon(aes(ymin = probability - se,
                  ymax = probability + se,
                  fill = NeriticOceanic), alpha = 0.3) +
  labs(x = "Trophic Level", y = "Probability of Occurrence", title = "Probability of Plastic Occurrence by Trophic Level According to Neritic-Oceanic Habitat") +
  theme_bw()


```


## Predictive Model 3

```{r}


trophic_vector <- rep(seq(from = 2, to = 5, by = 0.1), 3)

feeding_vector <- c(rep("BP", 93))

neritic_oceanic_vector <- rep("N-O", 93)

bentho_pelagic_vector <- c(rep("B", 31),
                 rep("P", 31),
                rep("BP", 31))

data_pred <- data.frame(trophic_vector, neritic_oceanic_vector, bentho_pelagic_vector, feeding_vector)
colnames(data_pred) <- c("trophic_level", "Neritic_Oceanic", "Bentho_Pelagic", "feeding_strategy")

prediction <- predict(fish_mod_glm,
                      newdata = data_pred,
                      type = "response",
                      se.fit = TRUE)


data_fig <- data.frame(data_pred,
                       prediction$fit,
                       prediction$se.fit)


colnames(data_fig) <- c("trophic_vector", "neritic_oceanic", "BenthoPelagic", "feeding_strategy", "probability", "se")

library(ggplot2)

ggplot(data_fig, aes(x = trophic_vector,
                     y = probability)) +
  geom_line(aes(color = BenthoPelagic)) +
  geom_ribbon(aes(ymin = probability - se,
                  ymax = probability + se,
                  fill = BenthoPelagic), alpha = 0.3) +
  labs(x = "Trophic Level", y = "Probability of Occurrence", title = "Probability of Plastic Occurrence by Trophic Level According to Bentho-Pelagic Habitat") +
  theme_bw()

```

```{r}

mean(fish$FO)

var(fish$FO)

sd(fish$FO)

troph_dist <- ggplot(fish, aes(x=FO)) +
  geom_histogram(bins = 15) + # rice's rule 
  theme_bw() +
  theme(legend.position = "none") +
  labs(x="Frequency of Occurrence", y = "Count", title = "Histogram of Frequency of Occurrence Values")

troph_dist


```



```{r}

write.csv(fish,file='cleaner_fish_table_becca.csv')

```

